# **ACTIVIDAD 1**

In [8]:
pip install numpy

Requirement already satisfied: numpy in c:\users\bintu\anaconda3\envs\entorno_inesdi\lib\site-packages (2.1.3)Note: you may need to restart the kernel to use updated packages.

## 1. Creación Dataframe

In [1]:
import pandas as pd
df_url = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv')

A través de la función `pd.read_csv` importamos el Dataframe de la url indicada.

Para hacernos una idea de la estructura del Dataframe, utilizamos el print(df)

In [2]:
print(df_url)

        crim    zn  indus  chas    nox     rm   age     dis  rad  tax  \
0    0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296
1    0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242
2    0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242
3    0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222
4    0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222
..       ...   ...    ...   ...    ...    ...   ...     ...  ...  ...
501  0.06263   0.0  11.93     0  0.573  6.593  69.1  2.4786    1  273
502  0.04527   0.0  11.93     0  0.573  6.120  76.7  2.2875    1  273
503  0.06076   0.0  11.93     0  0.573  6.976  91.0  2.1675    1  273
504  0.10959   0.0  11.93     0  0.573  6.794  89.3  2.3889    1  273
505  0.04741   0.0  11.93     0  0.573  6.030  80.8  2.5050    1  273

     ptratio       b  lstat  medv
0       15.3  396.90   4.98  24.0
1       17.8  396.90   9.14  21.6
2       17.8  392.83   4.03  34.7
3       18.7  394.63   2.94  33.4
4       18.7  396.90   5.33  36.2
..       ...     ...    ...   ...
501     21.0  391.99   9.67  22.4
502     21.0  396.90   9.08  20.6
503     21.0  396.90   5.64  23.9
504     21.0  393.45   6.48  22.0
505     21.0  396.90   7.88  11.9

[506 rows x 14 columns]

## 2. Obtener las dimensiones de dicho Dataframe

In [3]:
df_url.shape

(506, 14)

A través de la función `shape` podemos observar de manera simplificada que nuestro Dataframe contiene 506 fila y 14 columnas.

## 3. Obtener el resumen estadístico de todas las columnas

In [5]:
df_url.describe(include='all')

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,b,lstat,medv
count,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000
mean,3.613524,11.363636,11.136779,0.069170,0.554695,6.284634,68.574901,3.795043,9.549407,408.237154,18.455534,356.674032,12.653063,22.532806
std,8.601545,23.322453,6.860353,0.253994,0.115878,0.702617,28.148861,2.105710,8.707259,168.537116,2.164946,91.294864,7.141062,9.197104
min,0.006320,0.000000,0.460000,0.000000,0.385000,3.561000,2.900000,1.129600,1.000000,187.000000,12.600000,0.320000,1.730000,5.000000
25%,0.082045,0.000000,5.190000,0.000000,0.449000,5.885500,45.025000,2.100175,4.000000,279.000000,17.400000,375.377500,6.950000,17.025000
50%,0.256510,0.000000,9.690000,0.000000,0.538000,6.208500,77.500000,3.207450,5.000000,330.000000,19.050000,391.440000,11.360000,21.200000
75%,3.677083,12.500000,18.100000,0.000000,0.624000,6.623500,94.075000,5.188425,24.000000,666.000000,20.200000,396.225000,16.955000,25.000000
max,88.976200,100.000000,27.740000,1.000000,0.871000,8.780000,100.000000,12.126500,24.000000,711.000000,22.000000,396.900000,37.970000,50.000000

A través de la función `.describe(inclued='all')`, podemos ver un resumen de los estadísticos básicos para nuestro Dataframe en todas las columnas que conforman el Dataframe.

## 4. Crear un segundo Dataframe a partir del fichero .csv solo con las columnas ‘crim’ y ‘medv’.  (Importante: No debe venir del Dataframe creado en el apartado 1)

In [9]:
import pandas as pd
df_url1 = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv', usecols=['crim', 'medv'])

Para que la creación no sea a partir de nuestro Dataframe creado en el primer apartado, importamos nuevamente el fichero csv y con la función `df_selected`, indicamos las columnas que queremos para nuestro nuevo Dataframe.

Utilizamos print para comprobar de manera visual el cósigo ejecutado anteriormente.

In [10]:
print(df_url1)

        crim  medv
0    0.00632  24.0
1    0.02731  21.6
2    0.02729  34.7
3    0.03237  33.4
4    0.06905  36.2
..       ...   ...
501  0.06263  22.4
502  0.04527  20.6
503  0.06076  23.9
504  0.10959  22.0
505  0.04741  11.9

[506 rows x 2 columns]

# **ACTIVIDAD 2**

*Creamos un DataFrame utilizando el fichero de la Url.*

In [19]:
import pandas as pd
df_url = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

* Hacemos una pequeña revisión de la estructura del Dataframe

In [20]:
print(df_url)

   Manufacturer    Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0         Acura  Integra    Small       12.9   15.9       18.8      25.0
1           NaN   Legend  Midsize       29.2   33.9       38.7      18.0
2          Audi       90  Compact       25.9   29.1       32.3      20.0
3          Audi      100  Midsize        NaN   37.7       44.6      19.0
4           BMW     535i  Midsize        NaN   30.0        NaN      22.0
..          ...      ...      ...        ...    ...        ...       ...
88   Volkswagen  Eurovan      Van       16.6   19.7       22.7      17.0
89   Volkswagen   Passat  Compact       17.6   20.0       22.4      21.0
90   Volkswagen  Corrado   Sporty       22.9   23.3       23.7      18.0
91        Volvo      240  Compact       21.8   22.7       23.5      21.0
92          NaN      850  Midsize       24.8   26.7       28.5      20.0

    MPG.highway             AirBags DriveTrain  ... Passengers  Length  \
0          31.0                 NaN      Front  ...        5.0   177.0
1          25.0  Driver & Passenger      Front  ...        5.0   195.0
2          26.0         Driver only      Front  ...        5.0   180.0
3          26.0  Driver & Passenger        NaN  ...        6.0   193.0
4          30.0                 NaN       Rear  ...        4.0   186.0
..          ...                 ...        ...  ...        ...     ...
88         21.0                 NaN      Front  ...        7.0   187.0
89         30.0                 NaN      Front  ...        5.0   180.0
90         25.0                 NaN      Front  ...        4.0   159.0
91         28.0         Driver only       Rear  ...        5.0   190.0
92         28.0  Driver & Passenger      Front  ...        5.0   184.0

    Wheelbase  Width  Turn.circle Rear.seat.room  Luggage.room  Weight  \
0       102.0   68.0         37.0           26.5           NaN  2705.0
1       115.0   71.0         38.0           30.0          15.0  3560.0
2       102.0   67.0         37.0           28.0          14.0  3375.0
3       106.0    NaN         37.0           31.0          17.0  3405.0
4       109.0   69.0         39.0           27.0          13.0  3640.0
..        ...    ...          ...            ...           ...     ...
88      115.0   72.0         38.0           34.0           NaN  3960.0
89      103.0   67.0         35.0           31.5          14.0  2985.0
90       97.0   66.0         36.0           26.0          15.0  2810.0
91      104.0   67.0         37.0           29.5          14.0  2985.0
92      105.0   69.0         38.0           30.0          15.0  3245.0

     Origin                Make
0   non-USA       Acura Integra
1   non-USA        Acura Legend
2   non-USA             Audi 90
3   non-USA            Audi 100
4   non-USA            BMW 535i
..      ...                 ...
88      NaN  Volkswagen Eurovan
89  non-USA   Volkswagen Passat
90  non-USA  Volkswagen Corrado
91  non-USA           Volvo 240
92  non-USA           Volvo 850

[93 rows x 27 columns]

## 1. Revisión valores nulos en el Dataframe. El comando que se utilice para este propósito deberá devolver únicamente un resultado binario, es decir, si hay o no presente nulos en el Dataframe

In [51]:
Valores_nulos = df_url.isnull().values.any()
print(Valores_nulos)

True

Revisión de valores nulos. Si es TRUE si que hay valores nulos, si es FALSE, no hay valores nulos.

## 2. Contar el número de nulos en cada columna

In [26]:
df_url.isnull().sum()

Manufacturer           4
Model                  1
Type                   3
Min.Price              7
Price                  2
Max.Price              5
MPG.city               9
MPG.highway            2
AirBags               38
DriveTrain             7
Cylinders              5
EngineSize             2
Horsepower             7
RPM                    3
Rev.per.mile           6
Man.trans.avail        5
Fuel.tank.capacity     8
Passengers             2
Length                 4
Wheelbase              1
Width                  6
Turn.circle            5
Rear.seat.room         4
Luggage.room          19
Weight                 7
Origin                 5
Make                   3
dtype: int64

Número de valores nulos en cada columna

## 3. ¿Cuál es el valor máximo de los precios (Columna ‘Price’) de un carro?

In [34]:
max_Price = df_url['Price'].max()
print(max_Price)

61.9

Valor máximo de la columna 'Price' es 61.9

## 4. Obtener, en un solo paso, los valores del fabricante, modelo y tipo ('Manufacturer','Model' y 'Type') del carro de mayor precio (obtenido en el apartado 3)

In [52]:
carro_mayor_precio = df_url.loc[df_url['Price'].idxmax(), ['Manufacturer', 'Model', 'Type']]

print(carro_mayor_precio)

Manufacturer    Mercedes-Benz
Model                    300E
Type                  Midsize
Name: 58, dtype: object

Se muestran los valores de las columnas `'Manufacturer'`, `'Model'`,`'Type'` en función del valor máximo de la columna `'Price'`.

Por si la duda, mostramos todo el Dataframe para comprobar que los códigos ejectados anteriormente son correctos.

In [48]:
pd.set_option('display.max_rows', None)  # Mostrar todas las filas
pd.set_option('display.max_columns', None)  # Mostrar todas las columnas

print(df_url)

     Manufacturer           Model     Type  Min.Price  Price  Max.Price  \
0           Acura         Integra    Small       12.9   15.9       18.8
1             NaN          Legend  Midsize       29.2   33.9       38.7
2            Audi              90  Compact       25.9   29.1       32.3
3            Audi             100  Midsize        NaN   37.7       44.6
4             BMW            535i  Midsize        NaN   30.0        NaN
5           Buick         Century  Midsize       14.2   15.7       17.3
6           Buick         LeSabre    Large       19.9   20.8        NaN
7           Buick      Roadmaster    Large       22.6   23.7       24.9
8           Buick         Riviera  Midsize       26.3   26.3       26.3
9        Cadillac         DeVille    Large       33.0   34.7       36.3
10       Cadillac         Seville  Midsize       37.5   40.1       42.7
11      Chevrolet        Cavalier  Compact        8.5   13.4       18.3
12      Chevrolet         Corsica  Compact       11.4   11.4       11.4
13      Chevrolet          Camaro   Sporty       13.4   15.1       16.8
14      Chevrolet          Lumina  Midsize       13.4   15.9       18.4
15      Chevrolet      Lumina_APV      Van       14.7   16.3       18.0
16      Chevrolet           Astro      Van       14.7   16.6       18.6
17      Chevrolet         Caprice    Large       18.0   18.8       19.6
18      Chevrolet        Corvette   Sporty       34.6   38.0       41.5
19            NaN        Concorde    Large       18.4   18.4       18.4
20       Chrysler         LeBaron  Compact       14.5   15.8       17.1
21       Chrysler        Imperial    Large       29.5   29.5       29.5
22          Dodge            Colt    Small        7.9    9.2       10.6
23          Dodge          Shadow    Small        8.4   11.3       14.2
24          Dodge          Spirit  Compact       11.9   13.3       14.7
25          Dodge         Caravan      Van        NaN   19.0       24.4
26          Dodge         Dynasty  Midsize       14.8   15.6       16.4
27          Dodge         Stealth   Sporty       18.5   25.8       33.1
28          Eagle          Summit    Small        7.9   12.2       16.5
29          Eagle          Vision    Large        NaN   19.3       21.2
30           Ford         Festiva    Small        6.9    7.4        7.9
31           Ford          Escort    Small        8.4   10.1       11.9
32           Ford           Tempo  Compact       10.4   11.3       12.2
33           Ford         Mustang   Sporty       10.8   15.9       21.0
34           Ford           Probe   Sporty       12.8   14.0       15.2
35           Ford        Aerostar      Van       14.5   19.9       25.3
36           Ford          Taurus  Midsize       15.6   20.2       24.8
37           Ford  Crown_Victoria    Large       20.1   20.9       21.7
38            Geo           Metro    Small        6.7    8.4       10.0
39            Geo           Storm   Sporty       11.5   12.5       13.5
40          Honda         Prelude   Sporty       17.0   19.8       22.7
41          Honda           Civic    Small        8.4   12.1       15.8
42          Honda          Accord  Compact       13.8   17.5       21.2
43        Hyundai           Excel    Small        6.8    8.0        9.2
44        Hyundai         Elantra    Small        9.0   10.0       11.0
45        Hyundai          Scoupe      NaN        9.1   10.0       11.0
46        Hyundai          Sonata  Midsize       12.4   13.9       15.3
47       Infiniti             Q45  Midsize       45.4   47.9        NaN
48          Lexus           ES300  Midsize       27.5   28.0       28.4
49            NaN           SC300  Midsize       34.7   35.2       35.6
50        Lincoln     Continental  Midsize       33.3   34.3       35.3
51        Lincoln        Town_Car    Large       34.4   36.1       37.8
52          Mazda             323    Small        7.4    8.3        9.1
53          Mazda         Protege    Small       10.9   11.6       12.3
54          Mazda             626  Compact       14.3   16.5       18.7
55          Mazda             MPV      Van       16.6   19.1       21.7
56          Mazda            RX-7   Sporty       32.5   32.5       32.5
57  Mercedes-Benz            190E  Compact       29.0   31.9       34.9
58  Mercedes-Benz            300E  Midsize       43.8   61.9       80.0
59        Mercury             NaN   Sporty       13.3   14.1       15.0
60        Mercury          Cougar  Midsize       14.9   14.9       14.9
61     Mitsubishi          Mirage    Small        7.7   10.3       12.9
62     Mitsubishi        Diamante  Midsize       22.4   26.1        NaN
63         Nissan          Sentra    Small        8.7   11.8       14.9
64         Nissan          Altima  Compact       13.0   15.7       18.3
65         Nissan           Quest      Van       16.7   19.1       21.5
66         Nissan          Maxima  Midsize       21.0   21.5       22.0
67     Oldsmobile         Achieva  Compact       13.0   13.5       14.0
68     Oldsmobile   Cutlass_Ciera  Midsize       14.2   16.3       18.4
69     Oldsmobile      Silhouette      Van       19.5   19.5       19.5
70     Oldsmobile    Eighty-Eight    Large       19.5   20.7       21.9
71       Plymouth           Laser   Sporty       11.4   14.4       17.4
72        Pontiac          LeMans    Small        NaN    9.0        9.9
73        Pontiac         Sunbird  Compact        9.4   11.1       12.8
74        Pontiac        Firebird      NaN       14.0   17.7       21.4
75        Pontiac      Grand_Prix  Midsize       15.4   18.5       21.6
76        Pontiac      Bonneville    Large       19.4   24.4       29.4
77           Saab             900  Compact       20.3   28.7       37.1
78         Saturn              SL    Small        9.2    NaN       12.9
79         Subaru           Justy    Small        7.3    8.4        9.5
80         Subaru          Loyale    Small       10.5   10.9       11.3
81         Subaru          Legacy  Compact       16.3   19.5       22.7
82         Suzuki           Swift      NaN        7.3    8.6        NaN
83         Toyota          Tercel    Small        NaN    9.8       11.8
84         Toyota          Celica   Sporty       14.2   18.4       22.6
85         Toyota           Camry  Midsize       15.2    NaN       21.2
86         Toyota          Previa      Van        NaN   22.7       26.6
87     Volkswagen             Fox    Small        8.7    9.1        9.5
88     Volkswagen         Eurovan      Van       16.6   19.7       22.7
89     Volkswagen          Passat  Compact       17.6   20.0       22.4
90     Volkswagen         Corrado   Sporty       22.9   23.3       23.7
91          Volvo             240  Compact       21.8   22.7       23.5
92            NaN             850  Midsize       24.8   26.7       28.5

    MPG.city  MPG.highway             AirBags DriveTrain Cylinders  \
0       25.0         31.0                 NaN      Front         4
1       18.0         25.0  Driver & Passenger      Front         6
2       20.0         26.0         Driver only      Front         6
3       19.0         26.0  Driver & Passenger        NaN         6
4       22.0         30.0                 NaN       Rear         4
5       22.0         31.0         Driver only        NaN         4
6       19.0         28.0         Driver only      Front         6
7       16.0         25.0         Driver only       Rear         6
8       19.0         27.0         Driver only      Front         6
9       16.0         25.0         Driver only      Front         8
10      16.0         25.0  Driver & Passenger      Front         8
11      25.0         36.0                 NaN        NaN         4
12      25.0         34.0         Driver only      Front       NaN
13      19.0         28.0  Driver & Passenger       Rear       NaN
14       NaN         29.0                 NaN      Front         4
15      18.0         23.0                 NaN      Front         6
16      15.0         20.0                 NaN        4WD         6
17      17.0         26.0         Driver only       Rear         8
18      17.0         25.0         Driver only       Rear         8
19      20.0         28.0  Driver & Passenger      Front         6
20      23.0         28.0  Driver & Passenger      Front         4
21      20.0         26.0         Driver only      Front         6
22      29.0         33.0                 NaN      Front         4
23      23.0         29.0         Driver only      Front         4
24      22.0         27.0         Driver only      Front         4
25      17.0         21.0         Driver only        4WD         6
26      21.0          NaN         Driver only      Front       NaN
27       NaN         24.0         Driver only        4WD         6
28      29.0         33.0                 NaN      Front         4
29      20.0         28.0  Driver & Passenger      Front         6
30      31.0         33.0                 NaN      Front         4
31      23.0         30.0                 NaN      Front         4
32      22.0         27.0                 NaN      Front         4
33      22.0         29.0         Driver only       Rear         4
34       NaN         30.0         Driver only      Front         4
35      15.0         20.0         Driver only        4WD         6
36      21.0         30.0         Driver only      Front         6
37      18.0         26.0         Driver only       Rear         8
38      46.0         50.0                 NaN      Front         3
39      30.0         36.0         Driver only      Front         4
40      24.0         31.0  Driver & Passenger      Front         4
41      42.0         46.0         Driver only      Front         4
42      24.0         31.0  Driver & Passenger      Front         4
43      29.0         33.0                 NaN      Front         4
44       NaN         29.0                 NaN      Front         4
45      26.0         34.0                 NaN      Front         4
46      20.0         27.0                 NaN      Front         4
47      17.0         22.0                 NaN       Rear         8
48      18.0         24.0         Driver only      Front         6
49      18.0         23.0  Driver & Passenger       Rear         6
50      17.0         26.0  Driver & Passenger        NaN         6
51      18.0         26.0  Driver & Passenger       Rear         8
52      29.0         37.0                 NaN      Front         4
53      28.0         36.0                 NaN      Front         4
54      26.0         34.0         Driver only      Front         4
55      18.0         24.0                 NaN        4WD         6
56      17.0         25.0         Driver only        NaN    rotary
57       NaN         29.0         Driver only       Rear         4
58      19.0         25.0  Driver & Passenger       Rear         6
59      23.0         26.0         Driver only      Front         4
60      19.0         26.0                 NaN       Rear         6
61      29.0          NaN                 NaN      Front         4
62      18.0         24.0         Driver only      Front         6
63      29.0         33.0         Driver only      Front       NaN
64      24.0         30.0         Driver only      Front         4
65      17.0         23.0                 NaN      Front         6
66      21.0         26.0         Driver only      Front         6
67      24.0         31.0                 NaN      Front         4
68      23.0         31.0         Driver only      Front         4
69      18.0         23.0                 NaN      Front         6
70       NaN         28.0         Driver only      Front         6
71       NaN         30.0                 NaN        4WD         4
72      31.0         41.0                 NaN      Front         4
73       NaN         31.0                 NaN        NaN         4
74      19.0         28.0  Driver & Passenger       Rear         6
75      19.0         27.0                 NaN      Front         6
76      19.0         28.0  Driver & Passenger      Front         6
77      20.0         26.0                 NaN      Front         4
78       NaN         38.0         Driver only      Front         4
79      33.0         37.0                 NaN        4WD         3
80      25.0         30.0                 NaN        4WD         4
81      23.0         30.0         Driver only        4WD         4
82      39.0         43.0                 NaN      Front         3
83      32.0         37.0         Driver only      Front         4
84      25.0         32.0                 NaN      Front         4
85      22.0         29.0         Driver only        NaN         4
86      18.0         22.0         Driver only        4WD         4
87      25.0         33.0                 NaN      Front         4
88      17.0         21.0                 NaN      Front         5
89      21.0         30.0                 NaN      Front         4
90      18.0         25.0                 NaN      Front         6
91      21.0         28.0         Driver only       Rear       NaN
92      20.0         28.0  Driver & Passenger      Front         5

    EngineSize  Horsepower     RPM  Rev.per.mile Man.trans.avail  \
0          1.8       140.0  6300.0        2890.0             Yes
1          3.2       200.0  5500.0        2335.0             Yes
2          2.8       172.0  5500.0        2280.0             Yes
3          NaN       172.0  5500.0        2535.0             NaN
4          3.5       208.0  5700.0        2545.0             Yes
5          2.2       110.0  5200.0        2565.0              No
6          3.8       170.0  4800.0           NaN              No
7          5.7       180.0  4000.0        1320.0              No
8          3.8       170.0  4800.0        1690.0              No
9          4.9       200.0  4100.0           NaN              No
10         4.6       295.0  6000.0        1985.0              No
11         2.2         NaN  5200.0        2380.0             Yes
12         2.2       110.0  5200.0        2665.0             Yes
13         3.4       160.0  4600.0        1805.0             Yes
14         2.2         NaN  5200.0        2595.0              No
15         3.8       170.0  4800.0        1690.0              No
16         4.3         NaN  4000.0        1790.0              No
17         5.0       170.0  4200.0        1350.0              No
18         5.7       300.0  5000.0        1450.0             Yes
19         3.3       153.0  5300.0        1990.0              No
20         3.0       141.0  5000.0        2090.0              No
21         3.3       147.0  4800.0        1785.0              No
22         1.5        92.0  6000.0        3285.0             Yes
23         2.2        93.0  4800.0           NaN             Yes
24         2.5       100.0  4800.0        2535.0             Yes
25         3.0       142.0  5000.0        1970.0              No
26         2.5       100.0  4800.0        2465.0              No
27         3.0       300.0  6000.0        2120.0             Yes
28         1.5        92.0  6000.0        2505.0             Yes
29         3.5         NaN  5800.0        1980.0              No
30         1.3        63.0  5000.0        3150.0             Yes
31         1.8       127.0  6500.0        2410.0             NaN
32         2.3        96.0  4200.0        2805.0             Yes
33         2.3       105.0  4600.0        2285.0             Yes
34         2.0       115.0  5500.0        2340.0             Yes
35         3.0       145.0  4800.0        2080.0             Yes
36         3.0         NaN  4800.0        1885.0              No
37         4.6       190.0  4200.0           NaN              No
38         1.0        55.0  5700.0        3755.0             NaN
39         1.6        90.0  5400.0        3250.0             Yes
40         2.3       160.0  5800.0        2855.0             Yes
41         1.5         NaN  5900.0        2650.0             Yes
42         2.2       140.0  5600.0           NaN             Yes
43         1.5        81.0  5500.0        2710.0             Yes
44         1.8       124.0  6000.0        2745.0             Yes
45         1.5        92.0  5550.0        2540.0             Yes
46         2.0       128.0  6000.0        2335.0             Yes
47         4.5       278.0  6000.0        1955.0              No
48         3.0       185.0     NaN        2325.0             Yes
49         3.0       225.0  6000.0        2510.0             Yes
50         3.8       160.0  4400.0        1835.0              No
51         4.6       210.0  4600.0        1840.0              No
52         1.6        82.0  5000.0        2370.0             Yes
53         1.8       103.0  5500.0        2220.0             Yes
54         2.5       164.0  5600.0        2505.0             Yes
55         3.0       155.0  5000.0        2240.0              No
56         1.3       255.0  6500.0        2325.0             Yes
57         2.3       130.0  5100.0        2425.0             Yes
58         3.2       217.0  5500.0        2220.0              No
59         1.6       100.0  5750.0        2475.0             Yes
60         3.8       140.0  3800.0        1730.0              No
61         1.5        92.0  6000.0        2505.0             Yes
62         3.0       202.0  6000.0        2210.0              No
63         1.6       110.0  6000.0        2435.0             Yes
64         2.4       150.0  5600.0        2130.0             Yes
65         3.0         NaN  4800.0        2065.0              No
66         3.0       160.0  5200.0        2045.0             NaN
67         2.3       155.0  6000.0        2380.0              No
68         2.2       110.0  5200.0        2565.0              No
69         3.8       170.0  4800.0        1690.0              No
70         3.8       170.0  4800.0        1570.0              No
71         1.8        92.0  5000.0        2360.0             Yes
72         1.6        74.0  5600.0        3130.0             Yes
73         2.0       110.0  5200.0        2665.0             Yes
74         NaN       160.0  4600.0        1805.0             Yes
75         3.4       200.0  5000.0        1890.0             Yes
76         3.8       170.0  4800.0        1565.0              No
77         2.1       140.0  6000.0        2910.0             Yes
78         1.9        85.0  5000.0        2145.0             Yes
79         1.2        73.0  5600.0        2875.0             Yes
80         1.8        90.0  5200.0        3375.0             Yes
81         2.2       130.0     NaN        2330.0             Yes
82         1.3        70.0  6000.0        3360.0             Yes
83         1.5        82.0  5200.0        3505.0             Yes
84         2.2       135.0     NaN        2405.0             Yes
85         2.2       130.0  5400.0        2340.0             NaN
86         2.4       138.0  5000.0        2515.0             Yes
87         1.8        81.0  5500.0        2550.0             Yes
88         2.5       109.0  4500.0        2915.0             Yes
89         2.0       134.0  5800.0        2685.0             Yes
90         2.8       178.0  5800.0        2385.0             Yes
91         2.3       114.0  5400.0        2215.0             Yes
92         2.4       168.0  6200.0           NaN             Yes

    Fuel.tank.capacity  Passengers  Length  Wheelbase  Width  Turn.circle  \
0                 13.2         5.0   177.0      102.0   68.0         37.0
1                 18.0         5.0   195.0      115.0   71.0         38.0
2                 16.9         5.0   180.0      102.0   67.0         37.0
3                 21.1         6.0   193.0      106.0    NaN         37.0
4                 21.1         4.0   186.0      109.0   69.0         39.0
5                 16.4         6.0   189.0      105.0   69.0         41.0
6                  NaN         6.0   200.0      111.0   74.0         42.0
7                 23.0         6.0   216.0      116.0   78.0         45.0
8                 18.8         5.0   198.0      108.0    NaN         41.0